### ISSUE TITLE
Getting `process is not defined` upon importing the library

### ISSUE THREAD

**Issue by Destaq** [milayek86/reactjs-star-rating#1]
Thank you for making this useful library! Only one I found which allows for vertical, half-filled stars 😁 .

That said, I'm having some trouble getting it to work with my React app, even when setting `"is_client";`.

I get the following message:

```
process is not defined
ReferenceError: process is not defined
    at i (http://localhost:3000/static/js/bundle.js:324570:9)
    at c (http://localhost:3000/static/js/bundle.js:324575:16)
    at http://localhost:3000/static/js/bundle.js:324448:18
    at http://localhost:3000/static/js/bundle.js:324644:6
    at n (http://localhost:3000/static/js/bundle.js:324139:10)
    at ./node_modules/@mil-rlib/reactjs-star-rating/dist/index.js (http://localhost:3000/static/js/bundle.js:324444:9)
    at options.factory (http://localhost:3000/static/js/bundle.js:345564:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:344985:32)
    at fn (http://localhost:3000/static/js/bundle.js:345222:21)
    at ./src/components/careers/XXX.jsx (http://localhost:3000/static/js/bundle.js:5711:87)
```

Not sure if you have an idea of what this might be caused by?

**Comment by Destaq** [comment]
This was an error with the React configuration, apologies. Keep up the good work 👍
